### ISSUE TITLE
[FEATURE] Apple Store's privacy manifest requires Admob SDK 11.2

### ISSUE THREAD

**Issue by abcjjy** [poingstudios/godot-admob-ios#97]
### Is your feature request related to a problem? If so, please describe.

Here is the doc from apple https://developer.apple.com/news/?id=pvszzano

Here is the doc from admob https://developers.google.com/admob/ios/privacy/data-disclosure

This is a requirement for distributing apps on App Store from May 1.

### What feature or improvement would you like to see?

Please update Admob SDK >= 11.2

**Comment by gumaciel** [comment]
Thank you for telling us this, we will update the version.

**Comment by gumaciel** [comment]
@abcjjy new version release with this change: v3.1.1

The new AdMob SDK version is 11.3: https://github.com/poingstudios/godot-admob-ios/commit/36692656f2ae42525ce606c2a2d224c88dbeb1f8#diff-831f04560b4bbaf98ebbed4ab352674ff2174434b4e5d6abc0ac310ae6ffda08

Please test it, you just need to re-download again from Godot Editor: 

![Screenshot 2024-05-05 at 19 27 57](https://github.com/poingstudios/godot-admob-ios/assets/20030153/649323f0-35f6-4887-bd0f-b1b7f0384c90)
![Screenshot 2024-05-05 at 19 28 16](https://github.com/poingstudios/godot-admob-ios/assets/20030153/f487ace1-1a39-4a7e-adfc-df0440ee329e)

Closing this issue since seems to be fixed, you can re-open any time, thanks!
